name: Fetch Data

# on:
#  push:
#    branches:
#    - master

# the workflow runs exactly 48 hours before the next deadline date
# for example, the deadline for gameweek 17 is 14 Dec 2019 11:30 UTC
# so the workflow will execute on 12 Dec 2019 11:30 UTC
on:
   schedule:
   - cron: '30 11 12 12 *'
   - cron: '30 11 19 12 *'
   - cron: '30 11 24 12 *'
   - cron: '30 11 26 12 *'
   - cron: '30 11 29 12 *'
   - cron: '0 19 8 1 *'
   - cron: '30 11 16 1 *'
   - cron: '30 18 19 1 *'
   - cron: '0 14 29 1 *'
   - cron: '0 14 6 2 *'
   - cron: '0 14 20 2 *'
   - cron: '0 14 27 2 *'
   - cron: '0 14 5 3 *'
   - cron: '0 14 12 3 *'
   - cron: '0 14 19 3 *'
   - cron: '0 13 2 4 *'
   - cron: '0 13 9 4 *'
   - cron: '0 13 16 4 *'
   - cron: '0 13 23 4 *'
   - cron: '0 13 30 4 *'
   - cron: '0 13 7 5 *'
   - cron: '0 13 15 5 *'

jobs:
  fetchData:
    
    env:
      REMOTE_BRANCH: master

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.5'
    
    - name: Install PIP packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch and organize data
      run: |
        python global_scraper.py
        python understat.py

      # change this config settings according to your need
    - name: Configure Git
      run: |
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Commit and Push
      run: |
        gameweek_id=`python gameweek.py`
        git add .
        git commit -m "gh-actions added gw${gameweek_id} data"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
